### ISSUE TITLE
Graph generation throws when using connectivity matrix [1 1; 1 1]

### ISSUE THREAD

**Issue by denkv** [dice-group/ldcbench#62]
A test case: https://github.com/dice-group/ldcbench/blob/ce9f112c72175a6585a3f47766ee8cce86b4a64a/ldcbench.api/src/test/java/org/dice_research/ldcbench/generate/RandomLODTest.java#L51-L56

**Comment by abdoudesouki** [comment]
done!

**Comment by denkv** [comment]
Still fails with only one node type and matrix like `[[1]]`.

https://github.com/dice-group/ldcbench/blob/1096725a75d4f06da0eaf4bf2944d9732e838178/ldcbench.api/src/test/java/org/dice_research/ldcbench/generate/RandomLODTest.java#L57-L62

Please update to the latest develop branch this time and unignore this test as well there.
